server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: mysql
    source: tiktok:tiktok123@tcp(mysql-master:3306)/tiktok?charset=utf8mb4&parseTime=True&loc=Local
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s
    
  redis:
    addr: redis-master:6379
    password: tiktok123
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
    pool_size: 100

  minio:
    endpoint: minio:9000
    access_key: minioadmin
    secret_key: minioadmin123
    bucket_name: tiktok-videos
    region: us-east-1
    use_ssl: false
    base_url: http://localhost:9000/tiktok-videos

  qiniu:
    access_key: your_qiniu_access_key
    secret_key: your_qiniu_secret_key
    bucket_name: tiktok-videos
    domain: your_domain.com
    region: z0
    use_https: true
    record_dir: /tmp/qiniu_resume  # 断点续传记录目录

  kafka:
    brokers:
      - kafka:29092
    producer:
      retry_max: 3
      batch_size: 16384
      linger_ms: 10
      compression_type: snappy
    consumer:
      group_id: tiktok-video-service
      auto_commit: true
      session_timeout: 10s
      fetch_min_bytes: 1
      fetch_max_wait: 500ms

jwt:
  secret: tiktok-jwt-secret-key-2024
  expire_time: 604800s

business:
  user:
    password_salt_length: 32
    username_min_length: 3
    username_max_length: 32
    password_min_length: 6
    password_max_length: 20

  video:
    max_file_size: 104857600  # 100MB
    max_title_length: 50
    default_feed_limit: 30
    supported_formats:
      - "video/mp4"
      - "video/avi"
      - "video/quicktime"
    cover_quality: 80
    cover_width: 720
    cover_height: 1280
    temp_dir: /tmp/video_process  # 视频处理临时目录

  storage:
    upload_timeout: 30s
    download_timeout: 10s
    presigned_url_expire: 3600s  # 1小时
    default_provider: qiniu  # qiniu or minio
    multipart_chunk_size: 4194304  # 4MB分片大小
    max_concurrent_uploads: 3      # 最大并发上传数

  kafka_topics:
    video_upload: video-upload-topic
    video_process: video-process-topic
    video_stats: video-stats-topic
    user_action: user-action-topic