server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: mysql
    source: tiktok:tiktok123@tcp(mysql-master:3306)/tiktok?charset=utf8mb4&parseTime=True&loc=Local
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s
    
  redis:
    addr: redis-master:6379
    password: tiktok123
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
    pool_size: 100

jwt:
  secret: tiktok-jwt-secret-key-2024
  expire_time: 604800s

business:
  user:
    password_salt_length: 32
    username_min_length: 3
    username_max_length: 32
    password_min_length: 6
    password_max_length: 20