server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s

data:
  database:
    driver: mysql
    source: tiktok:tiktok123@tcp(localhost:3306)/tiktok?charset=utf8mb4&parseTime=True&loc=Local
    max_idle_conns: 5
    max_open_conns: 20
    conn_max_lifetime: 300s
    
  redis:
    addr: localhost:6380
    password: tiktok123
    db: 1
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
    pool_size: 20

jwt:
  secret: test-jwt-secret-key-2024
  expire_time: 3600s

business:
  user:
    password_salt_length: 16
    username_min_length: 3
    username_max_length: 32
    password_min_length: 6
    password_max_length: 20