// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user/v1/user.proto

package v1

import (
	v1 "go-backend/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统计更新类型
type UpdateStatsType int32

const (
	UpdateStatsType_UPDATE_STATS_UNKNOWN         UpdateStatsType = 0
	UpdateStatsType_UPDATE_STATS_FOLLOW_COUNT    UpdateStatsType = 1 // 关注数
	UpdateStatsType_UPDATE_STATS_FOLLOWER_COUNT  UpdateStatsType = 2 // 粉丝数
	UpdateStatsType_UPDATE_STATS_WORK_COUNT      UpdateStatsType = 3 // 作品数
	UpdateStatsType_UPDATE_STATS_FAVORITE_COUNT  UpdateStatsType = 4 // 喜欢数
	UpdateStatsType_UPDATE_STATS_TOTAL_FAVORITED UpdateStatsType = 5 // 获赞数
)

// Enum value maps for UpdateStatsType.
var (
	UpdateStatsType_name = map[int32]string{
		0: "UPDATE_STATS_UNKNOWN",
		1: "UPDATE_STATS_FOLLOW_COUNT",
		2: "UPDATE_STATS_FOLLOWER_COUNT",
		3: "UPDATE_STATS_WORK_COUNT",
		4: "UPDATE_STATS_FAVORITE_COUNT",
		5: "UPDATE_STATS_TOTAL_FAVORITED",
	}
	UpdateStatsType_value = map[string]int32{
		"UPDATE_STATS_UNKNOWN":         0,
		"UPDATE_STATS_FOLLOW_COUNT":    1,
		"UPDATE_STATS_FOLLOWER_COUNT":  2,
		"UPDATE_STATS_WORK_COUNT":      3,
		"UPDATE_STATS_FAVORITE_COUNT":  4,
		"UPDATE_STATS_TOTAL_FAVORITED": 5,
	}
)

func (x UpdateStatsType) Enum() *UpdateStatsType {
	p := new(UpdateStatsType)
	*p = x
	return p
}

func (x UpdateStatsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStatsType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (UpdateStatsType) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[0]
}

func (x UpdateStatsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateStatsType.Descriptor instead.
func (UpdateStatsType) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

// 用户注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 用户注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          *RegisterData          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RegisterResponse) GetData() *RegisterData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // JWT Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterData) Reset() {
	*x = RegisterData{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterData) ProtoMessage() {}

func (x *RegisterData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterData.ProtoReflect.Descriptor instead.
func (*RegisterData) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 用户登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 用户登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          *LoginData             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LoginResponse) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // JWT Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取用户信息请求
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取用户信息响应
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          *GetUserData           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserResponse) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetUserResponse) GetData() *GetUserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserData) Reset() {
	*x = GetUserData{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserData) ProtoMessage() {}

func (x *GetUserData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserData.ProtoReflect.Descriptor instead.
func (*GetUserData) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserData) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

// 关注操作请求
type RelationActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                              // Token
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`     // 对方用户ID
	ActionType    int32                  `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // 1关注，2取消关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationActionRequest) Reset() {
	*x = RelationActionRequest{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationActionRequest) ProtoMessage() {}

func (x *RelationActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationActionRequest.ProtoReflect.Descriptor instead.
func (*RelationActionRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *RelationActionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RelationActionRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *RelationActionRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

// 关注操作响应
type RelationActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationActionResponse) Reset() {
	*x = RelationActionResponse{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationActionResponse) ProtoMessage() {}

func (x *RelationActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationActionResponse.ProtoReflect.Descriptor instead.
func (*RelationActionResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *RelationActionResponse) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

// 获取关注列表请求
type GetFollowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowListRequest) Reset() {
	*x = GetFollowListRequest{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowListRequest) ProtoMessage() {}

func (x *GetFollowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowListRequest.ProtoReflect.Descriptor instead.
func (*GetFollowListRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetFollowListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取关注列表响应
type GetFollowListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          *GetFollowListData     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowListResponse) Reset() {
	*x = GetFollowListResponse{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowListResponse) ProtoMessage() {}

func (x *GetFollowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowListResponse.ProtoReflect.Descriptor instead.
func (*GetFollowListResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetFollowListResponse) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetFollowListResponse) GetData() *GetFollowListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFollowListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserList      []*v1.User             `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"` // 关注用户列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowListData) Reset() {
	*x = GetFollowListData{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowListData) ProtoMessage() {}

func (x *GetFollowListData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowListData.ProtoReflect.Descriptor instead.
func (*GetFollowListData) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetFollowListData) GetUserList() []*v1.User {
	if x != nil {
		return x.UserList
	}
	return nil
}

// 获取粉丝列表请求
type GetFollowerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowerListRequest) Reset() {
	*x = GetFollowerListRequest{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowerListRequest) ProtoMessage() {}

func (x *GetFollowerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowerListRequest.ProtoReflect.Descriptor instead.
func (*GetFollowerListRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetFollowerListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowerListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取粉丝列表响应
type GetFollowerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          *GetFollowerListData   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowerListResponse) Reset() {
	*x = GetFollowerListResponse{}
	mi := &file_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowerListResponse) ProtoMessage() {}

func (x *GetFollowerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowerListResponse.ProtoReflect.Descriptor instead.
func (*GetFollowerListResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetFollowerListResponse) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetFollowerListResponse) GetData() *GetFollowerListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFollowerListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserList      []*v1.User             `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"` // 粉丝用户列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowerListData) Reset() {
	*x = GetFollowerListData{}
	mi := &file_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowerListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowerListData) ProtoMessage() {}

func (x *GetFollowerListData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowerListData.ProtoReflect.Descriptor instead.
func (*GetFollowerListData) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetFollowerListData) GetUserList() []*v1.User {
	if x != nil {
		return x.UserList
	}
	return nil
}

// 获取好友列表请求
type GetFriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListRequest) Reset() {
	*x = GetFriendListRequest{}
	mi := &file_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListRequest) ProtoMessage() {}

func (x *GetFriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListRequest.ProtoReflect.Descriptor instead.
func (*GetFriendListRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetFriendListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFriendListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取好友列表响应
type GetFriendListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          *GetFriendListData     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListResponse) Reset() {
	*x = GetFriendListResponse{}
	mi := &file_user_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListResponse) ProtoMessage() {}

func (x *GetFriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListResponse.ProtoReflect.Descriptor instead.
func (*GetFriendListResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetFriendListResponse) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetFriendListResponse) GetData() *GetFriendListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFriendListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserList      []*FriendUser          `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"` // 好友列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListData) Reset() {
	*x = GetFriendListData{}
	mi := &file_user_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListData) ProtoMessage() {}

func (x *GetFriendListData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListData.ProtoReflect.Descriptor instead.
func (*GetFriendListData) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetFriendListData) GetUserList() []*FriendUser {
	if x != nil {
		return x.UserList
	}
	return nil
}

// 好友用户信息(包含最新消息)
type FriendUser struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FollowCount     int64                  `protobuf:"varint,3,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"`
	FollowerCount   int64                  `protobuf:"varint,4,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	IsFollow        bool                   `protobuf:"varint,5,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
	Avatar          string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	BackgroundImage string                 `protobuf:"bytes,7,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"`
	Signature       string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	TotalFavorited  int64                  `protobuf:"varint,9,opt,name=total_favorited,json=totalFavorited,proto3" json:"total_favorited,omitempty"`
	WorkCount       int64                  `protobuf:"varint,10,opt,name=work_count,json=workCount,proto3" json:"work_count,omitempty"`
	FavoriteCount   int64                  `protobuf:"varint,11,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	Message         string                 `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`                 // 最新消息内容
	MsgType         int64                  `protobuf:"varint,13,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"` // 消息类型
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FriendUser) Reset() {
	*x = FriendUser{}
	mi := &file_user_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendUser) ProtoMessage() {}

func (x *FriendUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendUser.ProtoReflect.Descriptor instead.
func (*FriendUser) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{20}
}

func (x *FriendUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FriendUser) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *FriendUser) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *FriendUser) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

func (x *FriendUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FriendUser) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *FriendUser) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *FriendUser) GetTotalFavorited() int64 {
	if x != nil {
		return x.TotalFavorited
	}
	return 0
}

func (x *FriendUser) GetWorkCount() int64 {
	if x != nil {
		return x.WorkCount
	}
	return 0
}

func (x *FriendUser) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *FriendUser) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendUser) GetMsgType() int64 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

// gRPC内部调用 - 获取用户信息请求
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_user_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// gRPC内部调用 - 获取用户信息响应
type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_user_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserInfoResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

// gRPC内部调用 - 批量获取用户信息请求
type GetUsersInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersInfoRequest) Reset() {
	*x = GetUsersInfoRequest{}
	mi := &file_user_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoRequest) ProtoMessage() {}

func (x *GetUsersInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUsersInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{23}
}

func (x *GetUsersInfoRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// gRPC内部调用 - 批量获取用户信息响应
type GetUsersInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*v1.User             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersInfoResponse) Reset() {
	*x = GetUsersInfoResponse{}
	mi := &file_user_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoResponse) ProtoMessage() {}

func (x *GetUsersInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUsersInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{24}
}

func (x *GetUsersInfoResponse) GetUsers() []*v1.User {
	if x != nil {
		return x.Users
	}
	return nil
}

// gRPC内部调用 - 验证Token请求
type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_user_v1_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{25}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// gRPC内部调用 - 验证Token响应
type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_user_v1_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{26}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// gRPC内部调用 - 更新用户统计请求
type UpdateUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          UpdateStatsType        `protobuf:"varint,2,opt,name=type,proto3,enum=user.v1.UpdateStatsType" json:"type,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // 变化数量，可为负数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatsRequest) Reset() {
	*x = UpdateUserStatsRequest{}
	mi := &file_user_v1_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatsRequest) ProtoMessage() {}

func (x *UpdateUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatsRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateUserStatsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserStatsRequest) GetType() UpdateStatsType {
	if x != nil {
		return x.Type
	}
	return UpdateStatsType_UPDATE_STATS_UNKNOWN
}

func (x *UpdateUserStatsRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16common/v1/common.proto\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"j\n" +
	"\x10RegisterResponse\x12+\n" +
	"\x04base\x18\x01 \x01(\v2\x17.common.v1.BaseResponseR\x04base\x12)\n" +
	"\x04data\x18\x02 \x01(\v2\x15.user.v1.RegisterDataR\x04data\"=\n" +
	"\fRegisterData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"d\n" +
	"\rLoginResponse\x12+\n" +
	"\x04base\x18\x01 \x01(\v2\x17.common.v1.BaseResponseR\x04base\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.user.v1.LoginDataR\x04data\":\n" +
	"\tLoginData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"?\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"h\n" +
	"\x0fGetUserResponse\x12+\n" +
	"\x04base\x18\x01 \x01(\v2\x17.common.v1.BaseResponseR\x04base\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.user.v1.GetUserDataR\x04data\"2\n" +
	"\vGetUserData\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.common.v1.UserR\x04user\"l\n" +
	"\x15RelationActionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\x05R\n" +
	"actionType\"E\n" +
	"\x16RelationActionResponse\x12+\n" +
	"\x04base\x18\x01 \x01(\v2\x17.common.v1.BaseResponseR\x04base\"E\n" +
	"\x14GetFollowListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"t\n" +
	"\x15GetFollowListResponse\x12+\n" +
	"\x04base\x18\x01 \x01(\v2\x17.common.v1.BaseResponseR\x04base\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.user.v1.GetFollowListDataR\x04data\"A\n" +
	"\x11GetFollowListData\x12,\n" +
	"\tuser_list\x18\x01 \x03(\v2\x0f.common.v1.UserR\buserList\"G\n" +
	"\x16GetFollowerListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"x\n" +
	"\x17GetFollowerListResponse\x12+\n" +
	"\x04base\x18\x01 \x01(\v2\x17.common.v1.BaseResponseR\x04base\x120\n" +
	"\x04data\x18\x02 \x01(\v2\x1c.user.v1.GetFollowerListDataR\x04data\"C\n" +
	"\x13GetFollowerListData\x12,\n" +
	"\tuser_list\x18\x01 \x03(\v2\x0f.common.v1.UserR\buserList\"E\n" +
	"\x14GetFriendListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"t\n" +
	"\x15GetFriendListResponse\x12+\n" +
	"\x04base\x18\x01 \x01(\v2\x17.common.v1.BaseResponseR\x04base\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.user.v1.GetFriendListDataR\x04data\"E\n" +
	"\x11GetFriendListData\x120\n" +
	"\tuser_list\x18\x01 \x03(\v2\x13.user.v1.FriendUserR\buserList\"\x9c\x03\n" +
	"\n" +
	"FriendUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\ffollow_count\x18\x03 \x01(\x03R\vfollowCount\x12%\n" +
	"\x0efollower_count\x18\x04 \x01(\x03R\rfollowerCount\x12\x1b\n" +
	"\tis_follow\x18\x05 \x01(\bR\bisFollow\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\a \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12'\n" +
	"\x0ftotal_favorited\x18\t \x01(\x03R\x0etotalFavorited\x12\x1d\n" +
	"\n" +
	"work_count\x18\n" +
	" \x01(\x03R\tworkCount\x12%\n" +
	"\x0efavorite_count\x18\v \x01(\x03R\rfavoriteCount\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\x12\x19\n" +
	"\bmsg_type\x18\r \x01(\x03R\amsgType\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\":\n" +
	"\x13GetUserInfoResponse\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.common.v1.UserR\x04user\"0\n" +
	"\x13GetUsersInfoRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"=\n" +
	"\x14GetUsersInfoResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.common.v1.UserR\x05users\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"`\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"u\n" +
	"\x16UpdateUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.user.v1.UpdateStatsTypeR\x04type\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count*\xcb\x01\n" +
	"\x0fUpdateStatsType\x12\x18\n" +
	"\x14UPDATE_STATS_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19UPDATE_STATS_FOLLOW_COUNT\x10\x01\x12\x1f\n" +
	"\x1bUPDATE_STATS_FOLLOWER_COUNT\x10\x02\x12\x1b\n" +
	"\x17UPDATE_STATS_WORK_COUNT\x10\x03\x12\x1f\n" +
	"\x1bUPDATE_STATS_FAVORITE_COUNT\x10\x04\x12 \n" +
	"\x1cUPDATE_STATS_TOTAL_FAVORITED\x10\x052\xa6\b\n" +
	"\vUserService\x12a\n" +
	"\bRegister\x12\x18.user.v1.RegisterRequest\x1a\x19.user.v1.RegisterResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/douyin/user/register\x12U\n" +
	"\x05Login\x12\x15.user.v1.LoginRequest\x1a\x16.user.v1.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/douyin/user/login\x12R\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/douyin/user\x12r\n" +
	"\x0eRelationAction\x12\x1e.user.v1.RelationActionRequest\x1a\x1f.user.v1.RelationActionResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/douyin/relation/action\x12t\n" +
	"\rGetFollowList\x12\x1d.user.v1.GetFollowListRequest\x1a\x1e.user.v1.GetFollowListResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/douyin/relation/follow/list\x12|\n" +
	"\x0fGetFollowerList\x12\x1f.user.v1.GetFollowerListRequest\x1a .user.v1.GetFollowerListResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/douyin/relation/follower/list\x12t\n" +
	"\rGetFriendList\x12\x1d.user.v1.GetFriendListRequest\x1a\x1e.user.v1.GetFriendListResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/douyin/relation/friend/list\x12H\n" +
	"\vGetUserInfo\x12\x1b.user.v1.GetUserInfoRequest\x1a\x1c.user.v1.GetUserInfoResponse\x12K\n" +
	"\fGetUsersInfo\x12\x1c.user.v1.GetUsersInfoRequest\x1a\x1d.user.v1.GetUsersInfoResponse\x12H\n" +
	"\vVerifyToken\x12\x1b.user.v1.VerifyTokenRequest\x1a\x1c.user.v1.VerifyTokenResponse\x12J\n" +
	"\x0fUpdateUserStats\x12\x1f.user.v1.UpdateUserStatsRequest\x1a\x16.google.protobuf.EmptyB\x1bZ\x19go-backend/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_user_v1_user_proto_goTypes = []any{
	(UpdateStatsType)(0),            // 0: user.v1.UpdateStatsType
	(*RegisterRequest)(nil),         // 1: user.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 2: user.v1.RegisterResponse
	(*RegisterData)(nil),            // 3: user.v1.RegisterData
	(*LoginRequest)(nil),            // 4: user.v1.LoginRequest
	(*LoginResponse)(nil),           // 5: user.v1.LoginResponse
	(*LoginData)(nil),               // 6: user.v1.LoginData
	(*GetUserRequest)(nil),          // 7: user.v1.GetUserRequest
	(*GetUserResponse)(nil),         // 8: user.v1.GetUserResponse
	(*GetUserData)(nil),             // 9: user.v1.GetUserData
	(*RelationActionRequest)(nil),   // 10: user.v1.RelationActionRequest
	(*RelationActionResponse)(nil),  // 11: user.v1.RelationActionResponse
	(*GetFollowListRequest)(nil),    // 12: user.v1.GetFollowListRequest
	(*GetFollowListResponse)(nil),   // 13: user.v1.GetFollowListResponse
	(*GetFollowListData)(nil),       // 14: user.v1.GetFollowListData
	(*GetFollowerListRequest)(nil),  // 15: user.v1.GetFollowerListRequest
	(*GetFollowerListResponse)(nil), // 16: user.v1.GetFollowerListResponse
	(*GetFollowerListData)(nil),     // 17: user.v1.GetFollowerListData
	(*GetFriendListRequest)(nil),    // 18: user.v1.GetFriendListRequest
	(*GetFriendListResponse)(nil),   // 19: user.v1.GetFriendListResponse
	(*GetFriendListData)(nil),       // 20: user.v1.GetFriendListData
	(*FriendUser)(nil),              // 21: user.v1.FriendUser
	(*GetUserInfoRequest)(nil),      // 22: user.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),     // 23: user.v1.GetUserInfoResponse
	(*GetUsersInfoRequest)(nil),     // 24: user.v1.GetUsersInfoRequest
	(*GetUsersInfoResponse)(nil),    // 25: user.v1.GetUsersInfoResponse
	(*VerifyTokenRequest)(nil),      // 26: user.v1.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),     // 27: user.v1.VerifyTokenResponse
	(*UpdateUserStatsRequest)(nil),  // 28: user.v1.UpdateUserStatsRequest
	(*v1.BaseResponse)(nil),         // 29: common.v1.BaseResponse
	(*v1.User)(nil),                 // 30: common.v1.User
	(*emptypb.Empty)(nil),           // 31: google.protobuf.Empty
}
var file_user_v1_user_proto_depIdxs = []int32{
	29, // 0: user.v1.RegisterResponse.base:type_name -> common.v1.BaseResponse
	3,  // 1: user.v1.RegisterResponse.data:type_name -> user.v1.RegisterData
	29, // 2: user.v1.LoginResponse.base:type_name -> common.v1.BaseResponse
	6,  // 3: user.v1.LoginResponse.data:type_name -> user.v1.LoginData
	29, // 4: user.v1.GetUserResponse.base:type_name -> common.v1.BaseResponse
	9,  // 5: user.v1.GetUserResponse.data:type_name -> user.v1.GetUserData
	30, // 6: user.v1.GetUserData.user:type_name -> common.v1.User
	29, // 7: user.v1.RelationActionResponse.base:type_name -> common.v1.BaseResponse
	29, // 8: user.v1.GetFollowListResponse.base:type_name -> common.v1.BaseResponse
	14, // 9: user.v1.GetFollowListResponse.data:type_name -> user.v1.GetFollowListData
	30, // 10: user.v1.GetFollowListData.user_list:type_name -> common.v1.User
	29, // 11: user.v1.GetFollowerListResponse.base:type_name -> common.v1.BaseResponse
	17, // 12: user.v1.GetFollowerListResponse.data:type_name -> user.v1.GetFollowerListData
	30, // 13: user.v1.GetFollowerListData.user_list:type_name -> common.v1.User
	29, // 14: user.v1.GetFriendListResponse.base:type_name -> common.v1.BaseResponse
	20, // 15: user.v1.GetFriendListResponse.data:type_name -> user.v1.GetFriendListData
	21, // 16: user.v1.GetFriendListData.user_list:type_name -> user.v1.FriendUser
	30, // 17: user.v1.GetUserInfoResponse.user:type_name -> common.v1.User
	30, // 18: user.v1.GetUsersInfoResponse.users:type_name -> common.v1.User
	0,  // 19: user.v1.UpdateUserStatsRequest.type:type_name -> user.v1.UpdateStatsType
	1,  // 20: user.v1.UserService.Register:input_type -> user.v1.RegisterRequest
	4,  // 21: user.v1.UserService.Login:input_type -> user.v1.LoginRequest
	7,  // 22: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	10, // 23: user.v1.UserService.RelationAction:input_type -> user.v1.RelationActionRequest
	12, // 24: user.v1.UserService.GetFollowList:input_type -> user.v1.GetFollowListRequest
	15, // 25: user.v1.UserService.GetFollowerList:input_type -> user.v1.GetFollowerListRequest
	18, // 26: user.v1.UserService.GetFriendList:input_type -> user.v1.GetFriendListRequest
	22, // 27: user.v1.UserService.GetUserInfo:input_type -> user.v1.GetUserInfoRequest
	24, // 28: user.v1.UserService.GetUsersInfo:input_type -> user.v1.GetUsersInfoRequest
	26, // 29: user.v1.UserService.VerifyToken:input_type -> user.v1.VerifyTokenRequest
	28, // 30: user.v1.UserService.UpdateUserStats:input_type -> user.v1.UpdateUserStatsRequest
	2,  // 31: user.v1.UserService.Register:output_type -> user.v1.RegisterResponse
	5,  // 32: user.v1.UserService.Login:output_type -> user.v1.LoginResponse
	8,  // 33: user.v1.UserService.GetUser:output_type -> user.v1.GetUserResponse
	11, // 34: user.v1.UserService.RelationAction:output_type -> user.v1.RelationActionResponse
	13, // 35: user.v1.UserService.GetFollowList:output_type -> user.v1.GetFollowListResponse
	16, // 36: user.v1.UserService.GetFollowerList:output_type -> user.v1.GetFollowerListResponse
	19, // 37: user.v1.UserService.GetFriendList:output_type -> user.v1.GetFriendListResponse
	23, // 38: user.v1.UserService.GetUserInfo:output_type -> user.v1.GetUserInfoResponse
	25, // 39: user.v1.UserService.GetUsersInfo:output_type -> user.v1.GetUsersInfoResponse
	27, // 40: user.v1.UserService.VerifyToken:output_type -> user.v1.VerifyTokenResponse
	31, // 41: user.v1.UserService.UpdateUserStats:output_type -> google.protobuf.Empty
	31, // [31:42] is the sub-list for method output_type
	20, // [20:31] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		EnumInfos:         file_user_v1_user_proto_enumTypes,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
