// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: common/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 操作类型枚举
type ActionType int32

const (
	ActionType_ACTION_UNKNOWN  ActionType = 0
	ActionType_ACTION_LIKE     ActionType = 1 // 点赞
	ActionType_ACTION_UNLIKE   ActionType = 2 // 取消点赞
	ActionType_ACTION_FOLLOW   ActionType = 3 // 关注
	ActionType_ACTION_UNFOLLOW ActionType = 4 // 取消关注
	ActionType_ACTION_COMMENT  ActionType = 5 // 评论
	ActionType_ACTION_DELETE   ActionType = 6 // 删除
	ActionType_ACTION_SEND     ActionType = 7 // 发送
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_LIKE",
		2: "ACTION_UNLIKE",
		3: "ACTION_FOLLOW",
		4: "ACTION_UNFOLLOW",
		5: "ACTION_COMMENT",
		6: "ACTION_DELETE",
		7: "ACTION_SEND",
	}
	ActionType_value = map[string]int32{
		"ACTION_UNKNOWN":  0,
		"ACTION_LIKE":     1,
		"ACTION_UNLIKE":   2,
		"ACTION_FOLLOW":   3,
		"ACTION_UNFOLLOW": 4,
		"ACTION_COMMENT":  5,
		"ACTION_DELETE":   6,
		"ACTION_SEND":     7,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// 状态枚举
type Status int32

const (
	Status_STATUS_UNKNOWN  Status = 0
	Status_STATUS_ACTIVE   Status = 1 // 正常
	Status_STATUS_INACTIVE Status = 2 // 禁用
	Status_STATUS_DELETED  Status = 3 // 删除
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
		3: "STATUS_DELETED",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":  0,
		"STATUS_ACTIVE":   1,
		"STATUS_INACTIVE": 2,
		"STATUS_DELETED":  3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

// 视频状态枚举
type VideoStatus int32

const (
	VideoStatus_VIDEO_UNKNOWN    VideoStatus = 0
	VideoStatus_VIDEO_PUBLISHED  VideoStatus = 1 // 已发布
	VideoStatus_VIDEO_PRIVATE    VideoStatus = 2 // 私密
	VideoStatus_VIDEO_PROCESSING VideoStatus = 3 // 处理中
	VideoStatus_VIDEO_FAILED     VideoStatus = 4 // 处理失败
)

// Enum value maps for VideoStatus.
var (
	VideoStatus_name = map[int32]string{
		0: "VIDEO_UNKNOWN",
		1: "VIDEO_PUBLISHED",
		2: "VIDEO_PRIVATE",
		3: "VIDEO_PROCESSING",
		4: "VIDEO_FAILED",
	}
	VideoStatus_value = map[string]int32{
		"VIDEO_UNKNOWN":    0,
		"VIDEO_PUBLISHED":  1,
		"VIDEO_PRIVATE":    2,
		"VIDEO_PROCESSING": 3,
		"VIDEO_FAILED":     4,
	}
)

func (x VideoStatus) Enum() *VideoStatus {
	p := new(VideoStatus)
	*p = x
	return p
}

func (x VideoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[2].Descriptor()
}

func (VideoStatus) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[2]
}

func (x VideoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoStatus.Descriptor instead.
func (VideoStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{2}
}

// 消息类型枚举
type MessageType int32

const (
	MessageType_MESSAGE_UNKNOWN MessageType = 0
	MessageType_MESSAGE_TEXT    MessageType = 1 // 文本消息
	MessageType_MESSAGE_IMAGE   MessageType = 2 // 图片消息
	MessageType_MESSAGE_VIDEO   MessageType = 3 // 视频消息
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_UNKNOWN",
		1: "MESSAGE_TEXT",
		2: "MESSAGE_IMAGE",
		3: "MESSAGE_VIDEO",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_UNKNOWN": 0,
		"MESSAGE_TEXT":    1,
		"MESSAGE_IMAGE":   2,
		"MESSAGE_VIDEO":   3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[3].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[3]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{3}
}

// 错误码常量
type ErrorCode int32

const (
	ErrorCode_SUCCESS ErrorCode = 0
	// 通用错误 10xxx
	ErrorCode_PARAM_ERROR       ErrorCode = 10001
	ErrorCode_TOKEN_INVALID     ErrorCode = 10002
	ErrorCode_TOKEN_EXPIRED     ErrorCode = 10003
	ErrorCode_PERMISSION_DENIED ErrorCode = 10004
	ErrorCode_RATE_LIMIT        ErrorCode = 10005
	ErrorCode_SERVER_ERROR      ErrorCode = 50000
	// 用户错误 20xxx
	ErrorCode_USER_NOT_EXIST  ErrorCode = 20001
	ErrorCode_USER_EXIST      ErrorCode = 20002
	ErrorCode_PASSWORD_ERROR  ErrorCode = 20003
	ErrorCode_REGISTER_FAILED ErrorCode = 20004
	// 视频错误 30xxx
	ErrorCode_VIDEO_NOT_EXIST   ErrorCode = 30001
	ErrorCode_VIDEO_UPLOAD_FAIL ErrorCode = 30002
	ErrorCode_VIDEO_FORMAT_ERR  ErrorCode = 30003
	ErrorCode_VIDEO_SIZE_ERR    ErrorCode = 30004
	// 社交错误 40xxx
	ErrorCode_ALREADY_FOLLOW    ErrorCode = 40001
	ErrorCode_NOT_FOLLOW        ErrorCode = 40002
	ErrorCode_ALREADY_LIKE      ErrorCode = 40003
	ErrorCode_NOT_LIKE          ErrorCode = 40004
	ErrorCode_COMMENT_NOT_EXIST ErrorCode = 40005
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:     "SUCCESS",
		10001: "PARAM_ERROR",
		10002: "TOKEN_INVALID",
		10003: "TOKEN_EXPIRED",
		10004: "PERMISSION_DENIED",
		10005: "RATE_LIMIT",
		50000: "SERVER_ERROR",
		20001: "USER_NOT_EXIST",
		20002: "USER_EXIST",
		20003: "PASSWORD_ERROR",
		20004: "REGISTER_FAILED",
		30001: "VIDEO_NOT_EXIST",
		30002: "VIDEO_UPLOAD_FAIL",
		30003: "VIDEO_FORMAT_ERR",
		30004: "VIDEO_SIZE_ERR",
		40001: "ALREADY_FOLLOW",
		40002: "NOT_FOLLOW",
		40003: "ALREADY_LIKE",
		40004: "NOT_LIKE",
		40005: "COMMENT_NOT_EXIST",
	}
	ErrorCode_value = map[string]int32{
		"SUCCESS":           0,
		"PARAM_ERROR":       10001,
		"TOKEN_INVALID":     10002,
		"TOKEN_EXPIRED":     10003,
		"PERMISSION_DENIED": 10004,
		"RATE_LIMIT":        10005,
		"SERVER_ERROR":      50000,
		"USER_NOT_EXIST":    20001,
		"USER_EXIST":        20002,
		"PASSWORD_ERROR":    20003,
		"REGISTER_FAILED":   20004,
		"VIDEO_NOT_EXIST":   30001,
		"VIDEO_UPLOAD_FAIL": 30002,
		"VIDEO_FORMAT_ERR":  30003,
		"VIDEO_SIZE_ERR":    30004,
		"ALREADY_FOLLOW":    40001,
		"NOT_FOLLOW":        40002,
		"ALREADY_LIKE":      40003,
		"NOT_LIKE":          40004,
		"COMMENT_NOT_EXIST": 40005,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[4].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[4]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{4}
}

// 通用响应结构
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0成功
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BaseResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// 分页请求
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 页码，从1开始
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 分页响应
type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                    // 总数
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // 是否有更多
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 用户信息
type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FollowCount     int64                  `protobuf:"varint,3,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"`
	FollowerCount   int64                  `protobuf:"varint,4,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	IsFollow        bool                   `protobuf:"varint,5,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
	Avatar          string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	BackgroundImage string                 `protobuf:"bytes,7,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"`
	Signature       string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	TotalFavorited  int64                  `protobuf:"varint,9,opt,name=total_favorited,json=totalFavorited,proto3" json:"total_favorited,omitempty"`
	WorkCount       int64                  `protobuf:"varint,10,opt,name=work_count,json=workCount,proto3" json:"work_count,omitempty"`
	FavoriteCount   int64                  `protobuf:"varint,11,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *User) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *User) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *User) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *User) GetTotalFavorited() int64 {
	if x != nil {
		return x.TotalFavorited
	}
	return 0
}

func (x *User) GetWorkCount() int64 {
	if x != nil {
		return x.WorkCount
	}
	return 0
}

func (x *User) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

// 视频信息
type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author        *User                  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	PlayUrl       string                 `protobuf:"bytes,3,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	FavoriteCount int64                  `protobuf:"varint,5,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,6,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	IsFavorite    bool                   `protobuf:"varint,7,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Video) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Video) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 评论信息
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateDate    string                 `protobuf:"bytes,4,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	LikeCount     int64                  `protobuf:"varint,5,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ReplyCount    int64                  `protobuf:"varint,6,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetCreateDate() string {
	if x != nil {
		return x.CreateDate
	}
	return ""
}

func (x *Comment) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

// 消息信息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime    int64                  `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_common_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *Message) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// Token信息
type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_common_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *TokenInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TokenInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TokenInfo) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

// 文件信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_common_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *FileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_common_v1_common_proto protoreflect.FileDescriptor

const file_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/common.proto\x12\tcommon.v1\"N\n" +
	"\fBaseResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"5\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"?\n" +
	"\fPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xe1\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\ffollow_count\x18\x03 \x01(\x03R\vfollowCount\x12%\n" +
	"\x0efollower_count\x18\x04 \x01(\x03R\rfollowerCount\x12\x1b\n" +
	"\tis_follow\x18\x05 \x01(\bR\bisFollow\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\a \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12'\n" +
	"\x0ftotal_favorited\x18\t \x01(\x03R\x0etotalFavorited\x12\x1d\n" +
	"\n" +
	"work_count\x18\n" +
	" \x01(\x03R\tworkCount\x12%\n" +
	"\x0efavorite_count\x18\v \x01(\x03R\rfavoriteCount\"\x9a\x02\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x06author\x18\x02 \x01(\v2\x0f.common.v1.UserR\x06author\x12\x19\n" +
	"\bplay_url\x18\x03 \x01(\tR\aplayUrl\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12%\n" +
	"\x0efavorite_count\x18\x05 \x01(\x03R\rfavoriteCount\x12#\n" +
	"\rcomment_count\x18\x06 \x01(\x03R\fcommentCount\x12\x1f\n" +
	"\vis_favorite\x18\a \x01(\bR\n" +
	"isFavorite\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"\xb9\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\x04user\x18\x02 \x01(\v2\x0f.common.v1.UserR\x04user\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_date\x18\x04 \x01(\tR\n" +
	"createDate\x12\x1d\n" +
	"\n" +
	"like_count\x18\x05 \x01(\x03R\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\x06 \x01(\x03R\n" +
	"replyCount\"\x94\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x03R\n" +
	"fromUserId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\x03R\n" +
	"createTime\"a\n" +
	"\tTokenInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x03R\n" +
	"expireTime\"o\n" +
	"\bFileInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url*\xa4\x01\n" +
	"\n" +
	"ActionType\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vACTION_LIKE\x10\x01\x12\x11\n" +
	"\rACTION_UNLIKE\x10\x02\x12\x11\n" +
	"\rACTION_FOLLOW\x10\x03\x12\x13\n" +
	"\x0fACTION_UNFOLLOW\x10\x04\x12\x12\n" +
	"\x0eACTION_COMMENT\x10\x05\x12\x11\n" +
	"\rACTION_DELETE\x10\x06\x12\x0f\n" +
	"\vACTION_SEND\x10\a*X\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x12\x12\n" +
	"\x0eSTATUS_DELETED\x10\x03*p\n" +
	"\vVideoStatus\x12\x11\n" +
	"\rVIDEO_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fVIDEO_PUBLISHED\x10\x01\x12\x11\n" +
	"\rVIDEO_PRIVATE\x10\x02\x12\x14\n" +
	"\x10VIDEO_PROCESSING\x10\x03\x12\x10\n" +
	"\fVIDEO_FAILED\x10\x04*Z\n" +
	"\vMessageType\x12\x13\n" +
	"\x0fMESSAGE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fMESSAGE_TEXT\x10\x01\x12\x11\n" +
	"\rMESSAGE_IMAGE\x10\x02\x12\x11\n" +
	"\rMESSAGE_VIDEO\x10\x03*\xa7\x03\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x10\n" +
	"\vPARAM_ERROR\x10\x91N\x12\x12\n" +
	"\rTOKEN_INVALID\x10\x92N\x12\x12\n" +
	"\rTOKEN_EXPIRED\x10\x93N\x12\x16\n" +
	"\x11PERMISSION_DENIED\x10\x94N\x12\x0f\n" +
	"\n" +
	"RATE_LIMIT\x10\x95N\x12\x12\n" +
	"\fSERVER_ERROR\x10І\x03\x12\x14\n" +
	"\x0eUSER_NOT_EXIST\x10\xa1\x9c\x01\x12\x10\n" +
	"\n" +
	"USER_EXIST\x10\xa2\x9c\x01\x12\x14\n" +
	"\x0ePASSWORD_ERROR\x10\xa3\x9c\x01\x12\x15\n" +
	"\x0fREGISTER_FAILED\x10\xa4\x9c\x01\x12\x15\n" +
	"\x0fVIDEO_NOT_EXIST\x10\xb1\xea\x01\x12\x17\n" +
	"\x11VIDEO_UPLOAD_FAIL\x10\xb2\xea\x01\x12\x16\n" +
	"\x10VIDEO_FORMAT_ERR\x10\xb3\xea\x01\x12\x14\n" +
	"\x0eVIDEO_SIZE_ERR\x10\xb4\xea\x01\x12\x14\n" +
	"\x0eALREADY_FOLLOW\x10\xc1\xb8\x02\x12\x10\n" +
	"\n" +
	"NOT_FOLLOW\x10¸\x02\x12\x12\n" +
	"\fALREADY_LIKE\x10ø\x02\x12\x0e\n" +
	"\bNOT_LIKE\x10ĸ\x02\x12\x17\n" +
	"\x11COMMENT_NOT_EXIST\x10Ÿ\x02B\x1dZ\x1bgo-backend/api/common/v1;v1b\x06proto3"

var (
	file_common_v1_common_proto_rawDescOnce sync.Once
	file_common_v1_common_proto_rawDescData []byte
)

func file_common_v1_common_proto_rawDescGZIP() []byte {
	file_common_v1_common_proto_rawDescOnce.Do(func() {
		file_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)))
	})
	return file_common_v1_common_proto_rawDescData
}

var file_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_v1_common_proto_goTypes = []any{
	(ActionType)(0),      // 0: common.v1.ActionType
	(Status)(0),          // 1: common.v1.Status
	(VideoStatus)(0),     // 2: common.v1.VideoStatus
	(MessageType)(0),     // 3: common.v1.MessageType
	(ErrorCode)(0),       // 4: common.v1.ErrorCode
	(*BaseResponse)(nil), // 5: common.v1.BaseResponse
	(*PageRequest)(nil),  // 6: common.v1.PageRequest
	(*PageResponse)(nil), // 7: common.v1.PageResponse
	(*User)(nil),         // 8: common.v1.User
	(*Video)(nil),        // 9: common.v1.Video
	(*Comment)(nil),      // 10: common.v1.Comment
	(*Message)(nil),      // 11: common.v1.Message
	(*TokenInfo)(nil),    // 12: common.v1.TokenInfo
	(*FileInfo)(nil),     // 13: common.v1.FileInfo
}
var file_common_v1_common_proto_depIdxs = []int32{
	8, // 0: common.v1.Video.author:type_name -> common.v1.User
	8, // 1: common.v1.Comment.user:type_name -> common.v1.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_v1_common_proto_init() }
func file_common_v1_common_proto_init() {
	if File_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_common_proto_goTypes,
		DependencyIndexes: file_common_v1_common_proto_depIdxs,
		EnumInfos:         file_common_v1_common_proto_enumTypes,
		MessageInfos:      file_common_v1_common_proto_msgTypes,
	}.Build()
	File_common_v1_common_proto = out.File
	file_common_v1_common_proto_goTypes = nil
	file_common_v1_common_proto_depIdxs = nil
}
