// Code generated by mockery v2.53.4. DO NOT EDIT.

package biz

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: _a0, _a1
func (_m *MockUserRepo) CreateUser(_a0 context.Context, _a1 *User) (*User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *User) (*User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *User) *User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *User) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *User
func (_e *MockUserRepo_Expecter) CreateUser(_a0 interface{}, _a1 interface{}) *MockUserRepo_CreateUser_Call {
	return &MockUserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", _a0, _a1)}
}

func (_c *MockUserRepo_CreateUser_Call) Run(run func(_a0 context.Context, _a1 *User)) *MockUserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*User))
	})
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) Return(_a0 *User, _a1 error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) RunAndReturn(run func(context.Context, *User) (*User, error)) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: _a0, _a1
func (_m *MockUserRepo) GetUser(_a0 context.Context, _a1 int64) (*User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserRepo_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
func (_e *MockUserRepo_Expecter) GetUser(_a0 interface{}, _a1 interface{}) *MockUserRepo_GetUser_Call {
	return &MockUserRepo_GetUser_Call{Call: _e.mock.On("GetUser", _a0, _a1)}
}

func (_c *MockUserRepo_GetUser_Call) Run(run func(_a0 context.Context, _a1 int64)) *MockUserRepo_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserRepo_GetUser_Call) Return(_a0 *User, _a1 error) *MockUserRepo_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_GetUser_Call) RunAndReturn(run func(context.Context, int64) (*User, error)) *MockUserRepo_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function with given fields: _a0, _a1
func (_m *MockUserRepo) GetUserByUsername(_a0 context.Context, _a1 string) (*User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUserRepo_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockUserRepo_Expecter) GetUserByUsername(_a0 interface{}, _a1 interface{}) *MockUserRepo_GetUserByUsername_Call {
	return &MockUserRepo_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", _a0, _a1)}
}

func (_c *MockUserRepo_GetUserByUsername_Call) Run(run func(_a0 context.Context, _a1 string)) *MockUserRepo_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepo_GetUserByUsername_Call) Return(_a0 *User, _a1 error) *MockUserRepo_GetUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_GetUserByUsername_Call) RunAndReturn(run func(context.Context, string) (*User, error)) *MockUserRepo_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: _a0, _a1
func (_m *MockUserRepo) GetUsers(_a0 context.Context, _a1 []int64) ([]*User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]*User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []*User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUserRepo_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []int64
func (_e *MockUserRepo_Expecter) GetUsers(_a0 interface{}, _a1 interface{}) *MockUserRepo_GetUsers_Call {
	return &MockUserRepo_GetUsers_Call{Call: _e.mock.On("GetUsers", _a0, _a1)}
}

func (_c *MockUserRepo_GetUsers_Call) Run(run func(_a0 context.Context, _a1 []int64)) *MockUserRepo_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockUserRepo_GetUsers_Call) Return(_a0 []*User, _a1 error) *MockUserRepo_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_GetUsers_Call) RunAndReturn(run func(context.Context, []int64) ([]*User, error)) *MockUserRepo_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: _a0, _a1
func (_m *MockUserRepo) UpdateUser(_a0 context.Context, _a1 *User) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *User) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserRepo_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *User
func (_e *MockUserRepo_Expecter) UpdateUser(_a0 interface{}, _a1 interface{}) *MockUserRepo_UpdateUser_Call {
	return &MockUserRepo_UpdateUser_Call{Call: _e.mock.On("UpdateUser", _a0, _a1)}
}

func (_c *MockUserRepo_UpdateUser_Call) Run(run func(_a0 context.Context, _a1 *User)) *MockUserRepo_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*User))
	})
	return _c
}

func (_c *MockUserRepo_UpdateUser_Call) Return(_a0 error) *MockUserRepo_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_UpdateUser_Call) RunAndReturn(run func(context.Context, *User) error) *MockUserRepo_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStats provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserRepo) UpdateUserStats(_a0 context.Context, _a1 int64, _a2 *UserStats) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStats")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *UserStats) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_UpdateUserStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStats'
type MockUserRepo_UpdateUserStats_Call struct {
	*mock.Call
}

// UpdateUserStats is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
//   - _a2 *UserStats
func (_e *MockUserRepo_Expecter) UpdateUserStats(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserRepo_UpdateUserStats_Call {
	return &MockUserRepo_UpdateUserStats_Call{Call: _e.mock.On("UpdateUserStats", _a0, _a1, _a2)}
}

func (_c *MockUserRepo_UpdateUserStats_Call) Run(run func(_a0 context.Context, _a1 int64, _a2 *UserStats)) *MockUserRepo_UpdateUserStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*UserStats))
	})
	return _c
}

func (_c *MockUserRepo_UpdateUserStats_Call) Return(_a0 error) *MockUserRepo_UpdateUserStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_UpdateUserStats_Call) RunAndReturn(run func(context.Context, int64, *UserStats) error) *MockUserRepo_UpdateUserStats_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserRepo) VerifyPassword(_a0 context.Context, _a1 string, _a2 string) (*User, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*User, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *User); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockUserRepo_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockUserRepo_Expecter) VerifyPassword(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserRepo_VerifyPassword_Call {
	return &MockUserRepo_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", _a0, _a1, _a2)}
}

func (_c *MockUserRepo_VerifyPassword_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockUserRepo_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepo_VerifyPassword_Call) Return(_a0 *User, _a1 error) *MockUserRepo_VerifyPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_VerifyPassword_Call) RunAndReturn(run func(context.Context, string, string) (*User, error)) *MockUserRepo_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
